### ISSUE TITLE
Sample is not working

### ISSUE THREAD

**Issue by muhammadalkady** [HosseinYousefi/health_connect#1]
After cloning the sample:
1- `flutter pub get`
2- `flutter build apk`
3- `dart run jnigen --config jnigen.yaml`
although running `flutter build apk` I am getting 
```
[muhammad@alkady health_connect]$ flutter build apk && dart run jnigen --config jnigen.yaml

Running Gradle task 'assembleRelease'...                         1,955ms
✓  Built build/app/outputs/flutter-apk/app-release.apk (39.0MB).
(jnigen) INFO: ApiSummarizer.jar exists. Skipping build..
(jnigen) INFO: trying to obtain gradle classpaths...
Unhandled exception:


gradle exited with exit code 1
. This can be related to a known issue with gradle. Please run `flutter build apk` in ./. and try again

#0      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:117:7)
#1      generateJniBindings (package:jnigen/src/generate_bindings.dart:53:34)
<asynchronous suspension>
#2      main (file:///home/muhammad/.pub-cache/hosted/pub.dev/jnigen-0.3.0/bin/jnigen.dart:16:3)
<asynchronous suspension>

```
I have tried also `flutter pub clean` and `flutter pub get` before building the apk.

Thanks for your support.

**Comment by HosseinYousefi** [comment]
What is your Java version? Try using OpenJDK 17 or lower.

Find your java version by wrting `java --version` in your terminal.

**Comment by muhammadalkady** [comment]
Thank you very much. This solved my issue.
